version: '3.8'
services:
  app:
    build: .
    environment:
      - DB_NAME=my_database
      - DB_USER=my_user
      - DB_PASSWORD=my_password
      - DB_HOST=amvera-hackmir-cnpg-raz-rw
      - DB_PORT=5000
    ports:
      - "5000:5000"
